[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Specific redirects for Next.js app
[[redirects]]
  from = "/openpose-analyzer"
  to = "/openpose-analyzer"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard"
  to = "/dashboard"
  status = 200
  force = true

[[redirects]]
  from = "/progress-analytics"
  to = "/progress-analytics"
  status = 200
  force = true

# Fallback redirect for all other routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

# Force clear cache on each build
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = false
